layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 100
  exclude:
    archived: false
    forks: true
    projects:
      - HotelManagement
      - directus
      - TubiPlayer
      - fireadmin
      - ganttproject
      - udacity-course
      - 100-Days-Of-ML-Code
      - stanford-cs-229-machine-learning
      - job-system-cookbook
      - CommunityServer
      - Awesome_APIs
      - parkstash
      - ASE_Project
      - mobile-samples
      - bitx-android
      - taxi-app

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

#topics:
    #- name: Web design

  #- name: Sass
    #web_url: https://github.com/topics/sass
    #image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
